import type { Locale } from "@/lib/locales";

const en = {
  search: "Search this space",
  pauseMotion: "Pause background motion",
  playMotion: "Play background motion",
  searchPlaceholder: "A page, a project, a recent entry…",
  searchHint: "Find your way around my workshop.",
  pages: "Pages",
  projects: "Projects",
  posts: "Recent entries",
  noResults: "Nothing here yet. Try another word.",
  clear: "Clear search",
  close: "Close search",
  move: "move",
  open: "open",
  dismiss: "close",
  results: "results",
  role: "My contribution",
  sectionWork: "Selected work",
  sectionJournal: "Notebook",
  sectionPlay: "At my desk",
  deskSkills: ["React · CSS · Canvas", "APIs · Auth · Database", "Python · Data · Experiments"],
  contents: "In this entry",
  permalink: "Link to section",
  backTop: "Back to top",
  journalCount: "published entries",
  allProjects: "Explore the projects",
};
type StudioCopy = typeof en;
const uz: StudioCopy = {
  search: "Saytdan qidirish",
  pauseMotion: "Fon harakatini to‘xtatish",
  playMotion: "Fon harakatini yoqish",
  searchPlaceholder: "Sahifa, loyiha yoki so‘nggi yozuv…",
  searchHint: "Ustaxonamda kerakli joyni tez toping.",
  pages: "Sahifalar",
  projects: "Loyihalar",
  posts: "So‘nggi yozuvlar",
  noResults: "Mos natija topilmadi. Boshqa so‘zni sinab ko‘ring.",
  clear: "Qidiruvni tozalash",
  close: "Qidiruvni yopish",
  move: "tanlash",
  open: "ochish",
  dismiss: "yopish",
  results: "natija",
  role: "Mening hissam",
  sectionWork: "Tanlangan ishlar",
  sectionJournal: "Shaxsiy daftar",
  sectionPlay: "Ish stolimda",
  deskSkills: ["React · CSS · Canvas", "API · Auth · Baza", "Python · Ma’lumot · Tajriba"],
  contents: "Yozuv mazmuni",
  permalink: "Bo‘limga havola",
  backTop: "Yuqoriga qaytish",
  journalCount: "nashr qilingan yozuv",
  allProjects: "Loyihalar bilan tanishing",
};
const ru: StudioCopy = {
  search: "Поиск по сайту",
  pauseMotion: "Остановить анимацию фона",
  playMotion: "Включить анимацию фона",
  searchPlaceholder: "Страница, проект или недавняя запись…",
  searchHint: "Найдите нужное место в моей мастерской.",
  pages: "Страницы",
  projects: "Проекты",
  posts: "Недавние записи",
  noResults: "Ничего не найдено. Попробуйте другое слово.",
  clear: "Очистить поиск",
  close: "Закрыть поиск",
  move: "выбрать",
  open: "открыть",
  dismiss: "закрыть",
  results: "результатов",
  role: "Мой вклад",
  sectionWork: "Избранные работы",
  sectionJournal: "Личные заметки",
  sectionPlay: "На моём столе",
  deskSkills: [
    "React · CSS · Canvas",
    "API · Auth · База данных",
    "Python · Данные · Эксперименты",
  ],
  contents: "В этой записи",
  permalink: "Ссылка на раздел",
  backTop: "Вернуться наверх",
  journalCount: "опубликованных записей",
  allProjects: "Посмотрите проекты",
};
export const studio: Record<Locale, StudioCopy> = { en, uz, ru };
