import type { Locale } from "@/lib/locales";

const en = {
  blog: "Journal",
  lab: "Workshop",
  stamp: "A small corner of the internet",
  deskTitle: "Always a work in progress.",
  deskIntro: "Interfaces, the logic behind them, and things I’m figuring out along the way.",
  deskTabs: ["Frontend", "Backend", "Learning ML"],
  deskNotes: [
    "Small details. Better experiences.",
    "Connecting the parts that make it work.",
    "One concept, one experiment at a time.",
  ],
  deskLinks: ["Explore ProPaint", "Explore PromptPilot", "My learning exercises"],
  deskFooter: "Made with curiosity.",
  journalLabel: "From my notebook",
  journalTitle: "Building. Learning. Writing.",
  journalIntro:
    "Notes on what I’m working on, milestones along the way, and thoughts I want to keep.",
  journalAll: "All entries",
  journalEmpty: "A fresh page.",
  journalEmptyText:
    "This is where I’ll share my work, milestones and the things I learn. The first entry is on its way.",
  follow: "Follow on Telegram",
  search: "Search entries",
  searchPlaceholder: "A word, a project, an idea…",
  allTopics: "All topics",
  topics: { work: "Building", milestone: "Milestones", thoughts: "Thoughts", learning: "Learning" },
  noResults: "No matching entries. Try another word or topic.",
  reset: "Clear filters",
  minutes: "min read",
  read: "Read entry",
  rss: "RSS feed",
  back: "Back to the journal",
  updated: "Updated",
  author: "By Sardorbek Musurmonov",
  translations: "Also available in",
  translationTitle: "This translation is still on its way.",
  translationText: "You can read the published version in one of these languages.",
  preview: "Private draft preview",
  previewText: "Only this revision is shown. Publication is a separate action in the bot.",
  emptyDraft: "This field has not been filled in yet.",
  profileLabel: "One name, around the web",
  profileTitle: "Elsewhere, I’m sardorcodev.",
  profileIntro:
    "My projects, updates and other corners of the internet. Pick a place to say hello.",
  profileCode: "Code",
  profileSocial: "Social",
  profileVideo: "Video",
  profileContact: "Contact",
  profileEmpty: "More profiles will appear here.",
  labLabel: "A little room to play",
  labTitle: "Ideas you can touch.",
  labIntro:
    "Small experiments in interfaces and interaction. Try something, change it, see what happens.",
  canvasTitle: "Leave a little mark.",
  canvasIntro:
    "A tiny drawing surface inspired by my work on ProPaint. Your drawing stays in this browser.",
  canvasLabel:
    "Drawing area. Use a pointer or touch to draw; keyboard users can add a sample stroke.",
  canvasClear: "Clear drawing",
  canvasUndo: "Undo",
  canvasSample: "Add a stroke",
  canvasSave: "Save PNG",
  canvasSaved: "Drawing downloaded.",
  canvasCleared: "Drawing cleared.",
  canvasChanged: "Drawing updated.",
  ink: "Ink",
  ocean: "Ocean",
  clay: "Clay",
  leaf: "Leaf",
  width: "Brush width",
  canvasNote: "Canvas · pointer events · undo",
  labSource: "The project behind this experiment",
  labTeaser: "A little less scrolling. A little more doing.",
  labCta: "Open the workshop",
  nowLabel: "On my desk",
  nowTitle: "Learning by building.",
  nowText: "Frontend and backend projects, with small steps into Python and machine learning.",
  profileCta: "Find me around the web",
};
type Copy = typeof en;
const uz: Copy = {
  blog: "Blog",
  lab: "Ustaxona",
  stamp: "Internetdagi kichik ustaxonam",
  deskTitle: "Har doim izlanishda.",
  deskIntro: "Interfeyslar, ularning ortidagi mantiq va yo‘l-yo‘lakay o‘rganayotganlarim.",
  deskTabs: ["Frontend", "Backend", "ML o‘rganish"],
  deskNotes: [
    "Kichik detallar. Qulayroq interfeys.",
    "Ilovani ishlatadigan qismlarni bog‘lash.",
    "Bitta tushuncha, bitta kichik tajriba.",
  ],
  deskLinks: ["ProPaint bilan tanishish", "PromptPilot bilan tanishish", "O‘rganish mashqlarim"],
  deskFooter: "Qiziqish bilan yaratilgan.",
  journalLabel: "Shaxsiy qaydlarim",
  journalTitle: "Quraman. O‘rganaman. Yozaman.",
  journalIntro: "Qilayotgan ishlarim, yo‘ldagi yutuqlarim va saqlab qolishni istagan fikrlarim.",
  journalAll: "Barcha yozuvlar",
  journalEmpty: "Yangi sahifa.",
  journalEmptyText:
    "Bu yerda ishlarim, yutuqlarim va o‘rganganlarimni bo‘lishib boraman. Birinchi yozuv tez orada.",
  follow: "Telegramda kuzatish",
  search: "Yozuvlarni qidirish",
  searchPlaceholder: "So‘z, loyiha yoki biror fikr…",
  allTopics: "Barcha mavzular",
  topics: { work: "Ishlarim", milestone: "Yutuqlar", thoughts: "Fikrlar", learning: "O‘rganish" },
  noResults: "Mos yozuv topilmadi. Boshqa so‘z yoki mavzuni sinab ko‘ring.",
  reset: "Filtrlarni tozalash",
  minutes: "daqiqalik mutolaa",
  read: "Yozuvni o‘qish",
  rss: "RSS tasmasi",
  back: "Blogga qaytish",
  updated: "Yangilangan",
  author: "Muallif: Sardorbek Musurmonov",
  translations: "Boshqa tillarda",
  translationTitle: "Bu tarjima hali tayyorlanmoqda.",
  translationText: "Nashr qilingan variantni quyidagi tillardan birida o‘qishingiz mumkin.",
  preview: "Qoralamani shaxsiy ko‘rish",
  previewText: "Bu yerda faqat shu tahrir ko‘rsatiladi. Nashr qilish botda alohida tasdiqlanadi.",
  emptyDraft: "Bu maydon hali to‘ldirilmagan.",
  profileLabel: "Turli platformalarda bir nom",
  profileTitle: "Boshqa joylarda ham sardorcodev.",
  profileIntro:
    "Loyihalarim, yangiliklarim va internetdagi sahifalarim. Sizga qulay joyda bog‘lanamiz.",
  profileCode: "Kod",
  profileSocial: "Ijtimoiy tarmoq",
  profileVideo: "Video",
  profileContact: "Aloqa",
  profileEmpty: "Yangi profillar shu yerda paydo bo‘ladi.",
  labLabel: "Tajriba uchun kichik joy",
  labTitle: "G‘oyalarni sinab ko‘ring.",
  labIntro:
    "Interfeys va interaksiyalar bilan kichik tajribalar. Sinang, o‘zgartiring, natijani kuzating.",
  canvasTitle: "Bir iz qoldiring.",
  canvasIntro:
    "ProPaint loyihamdan ilhomlangan kichik chizish maydoni. Chizmangiz shu brauzerda qoladi.",
  canvasLabel:
    "Chizish maydoni. Sichqoncha yoki barmoq bilan chizing; klaviaturada namuna chizig‘ini qo‘shish tugmasidan foydalaning.",
  canvasClear: "Tozalash",
  canvasUndo: "Ortga",
  canvasSample: "Chiziq qo‘shish",
  canvasSave: "PNG saqlash",
  canvasSaved: "Chizma yuklab olindi.",
  canvasCleared: "Chizma tozalandi.",
  canvasChanged: "Chizma yangilandi.",
  ink: "Siyoh",
  ocean: "Moviy",
  clay: "Sopol",
  leaf: "Yashil",
  width: "Qalam qalinligi",
  canvasNote: "Canvas · pointer events · undo",
  labSource: "Tajriba ortidagi loyiha",
  labTeaser: "Kuzatishdan tajribaga bir qadam.",
  labCta: "Ustaxonani ochish",
  nowLabel: "Hozir ustimda ishlayapman",
  nowTitle: "Yaratib o‘rganaman.",
  nowText: "Frontend va backend loyihalari, Python hamda mashinaviy o‘rganishdagi kichik qadamlar.",
  profileCta: "Boshqa platformalardagi sahifalarim",
};
const ru: Copy = {
  blog: "Блог",
  lab: "Мастерская",
  stamp: "Моя небольшая мастерская в интернете",
  deskTitle: "Всегда в процессе.",
  deskIntro: "Интерфейсы, логика за ними и то, чему я учусь по пути.",
  deskTabs: ["Фронтенд", "Бэкенд", "Изучаю ML"],
  deskNotes: [
    "Небольшие детали. Удобные интерфейсы.",
    "Соединяю части, благодаря которым всё работает.",
    "Одно понятие, один небольшой эксперимент.",
  ],
  deskLinks: ["Посмотреть ProPaint", "Посмотреть PromptPilot", "Мои учебные упражнения"],
  deskFooter: "Создано с любопытством.",
  journalLabel: "Личные заметки",
  journalTitle: "Создаю. Учусь. Пишу.",
  journalIntro:
    "О том, над чем работаю, достижениях на этом пути и мыслях, которые хочется сохранить.",
  journalAll: "Все записи",
  journalEmpty: "Новая страница.",
  journalEmptyText:
    "Здесь я буду делиться работой, достижениями и тем, чему учусь. Первая запись скоро появится.",
  follow: "Следить в Telegram",
  search: "Поиск записей",
  searchPlaceholder: "Слово, проект или идея…",
  allTopics: "Все темы",
  topics: { work: "Работа", milestone: "Достижения", thoughts: "Мысли", learning: "Учёба" },
  noResults: "Записи не найдены. Попробуйте другое слово или тему.",
  reset: "Сбросить фильтры",
  minutes: "мин чтения",
  read: "Читать запись",
  rss: "RSS-лента",
  back: "Вернуться в блог",
  updated: "Обновлено",
  author: "Автор: Сардорбек Мусурмонов",
  translations: "На других языках",
  translationTitle: "Этот перевод ещё готовится.",
  translationText: "Опубликованную версию можно прочитать на одном из этих языков.",
  preview: "Личный просмотр черновика",
  previewText: "Здесь показана только эта редакция. Публикация отдельно подтверждается в боте.",
  emptyDraft: "Это поле пока не заполнено.",
  profileLabel: "Одно имя на разных платформах",
  profileTitle: "В других местах — тоже sardorcodev.",
  profileIntro:
    "Мои проекты, обновления и страницы в интернете. Выберите удобное место для общения.",
  profileCode: "Код",
  profileSocial: "Соцсеть",
  profileVideo: "Видео",
  profileContact: "Связь",
  profileEmpty: "Здесь появятся новые профили.",
  labLabel: "Немного места для экспериментов",
  labTitle: "Идеи, которые можно попробовать.",
  labIntro:
    "Небольшие эксперименты с интерфейсами и взаимодействием. Пробуйте, меняйте, наблюдайте.",
  canvasTitle: "Оставьте небольшой след.",
  canvasIntro:
    "Небольшой холст, вдохновлённый моим проектом ProPaint. Рисунок остаётся в этом браузере.",
  canvasLabel:
    "Область рисования. Рисуйте мышью или пальцем; для клавиатуры есть кнопка добавления штриха.",
  canvasClear: "Очистить",
  canvasUndo: "Отменить",
  canvasSample: "Добавить штрих",
  canvasSave: "Сохранить PNG",
  canvasSaved: "Рисунок скачан.",
  canvasCleared: "Холст очищен.",
  canvasChanged: "Рисунок обновлён.",
  ink: "Чернила",
  ocean: "Океан",
  clay: "Глина",
  leaf: "Лист",
  width: "Толщина кисти",
  canvasNote: "Canvas · pointer events · undo",
  labSource: "Проект, который вдохновил эксперимент",
  labTeaser: "От наблюдения — к эксперименту.",
  labCta: "Открыть мастерскую",
  nowLabel: "Сейчас на моём столе",
  nowTitle: "Учусь, создавая.",
  nowText: "Проекты на фронтенде и бэкенде, небольшие шаги в Python и машинном обучении.",
  profileCta: "Мои страницы на других платформах",
};
export const workshop: Record<Locale, Copy> = { en, uz, ru };
export type WorkshopCopy = Copy;
