import Link from "next/link";
import { Icon } from "@/components/icons";
import { navLinks, profiles, telegramUrl } from "@/lib/site";

export function Brand() {
  return <Link aria-label="sardorcodev home" className="flex shrink-0 items-center gap-3 font-bold tracking-[-0.04em] text-slate-950" href="/"><span aria-hidden="true" className="grid size-9 place-items-center rounded-xl bg-blue-600 text-sm text-white shadow-lg shadow-blue-200">S</span><span className="hidden text-lg sm:inline">sardorcodev<span className="text-blue-600">.</span></span></Link>;
}

export function Header() {
  return <header className="sticky top-0 z-50 border-b border-slate-200/80 bg-white/90 backdrop-blur-xl"><div className="mx-auto flex h-18 max-w-7xl items-center justify-between gap-3 px-5 sm:px-8"><Brand /><nav aria-label="Main navigation" className="hidden items-center gap-5 lg:flex xl:gap-7">{navLinks.map((link) => <Link className="text-sm font-semibold text-slate-600 hover:text-blue-600" href={link.href} key={link.href}>{link.label}</Link>)}</nav><a aria-label="Open the official sardorcodev Telegram channel in a new tab" className="inline-flex shrink-0 items-center gap-2 rounded-full bg-blue-600 px-4 py-2.5 text-xs font-bold text-white shadow-lg shadow-blue-200 hover:bg-blue-700 sm:text-sm" href={telegramUrl} rel="me noopener noreferrer" target="_blank"><Icon className="size-4" name="telegram" /><span className="sm:hidden">Telegram</span><span className="hidden sm:inline">Official Telegram</span></a></div><nav aria-label="Mobile navigation" className="flex gap-5 overflow-x-auto whitespace-nowrap border-t border-slate-100 px-5 py-3 text-xs font-bold text-slate-600 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden lg:hidden">{navLinks.map((link) => <Link className="shrink-0 hover:text-blue-600" href={link.href} key={link.href}>{link.label}</Link>)}</nav></header>;
}

export function Footer() {
  return <footer className="border-t border-slate-200 bg-slate-950 text-slate-300"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-12 sm:px-8 lg:grid-cols-[1.4fr_1fr_1fr]"><div><div className="text-lg font-bold tracking-[-0.04em] text-white">sardorcodev<span className="text-blue-500">.</span></div><p className="mt-4 max-w-md text-sm leading-6 text-slate-400">The official website of sardorcodev. Practical technology content, software development, AI systems, and automation.</p></div><div><h2 className="text-xs font-bold uppercase tracking-[0.18em] text-white">Navigate</h2><div className="mt-4 grid grid-cols-2 gap-3">{navLinks.map((link) => <Link className="text-sm hover:text-white" href={link.href} key={link.href}>{link.label}</Link>)}</div></div><div><h2 className="text-xs font-bold uppercase tracking-[0.18em] text-white">Official profiles</h2><div className="mt-4 flex flex-wrap gap-3">{profiles.map((profile) => <a aria-label={`${profile.name} official profile, opens in a new tab`} className="grid size-9 place-items-center rounded-lg bg-white/7 text-slate-300 hover:bg-blue-600 hover:text-white" href={profile.href} key={profile.name} rel="me noopener noreferrer" target="_blank"><Icon className="size-4" name={profile.icon} /></a>)}</div><a className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-blue-400 hover:text-blue-300" href={telegramUrl} rel="me noopener noreferrer" target="_blank"><Icon className="size-4" name="telegram" /> t.me/sardorcodev</a></div></div><div className="border-t border-white/10"><div className="mx-auto flex max-w-7xl flex-col gap-2 px-5 py-5 text-xs text-slate-500 sm:flex-row sm:justify-between sm:px-8"><p>&copy; {new Date().getFullYear()} sardorcodev. All rights reserved.</p><p>Founded by Sardorbek Musurmonov</p></div></div></footer>;
}
