import Link from "next/link";
import { Icon } from "@/components/icons";
import { profiles, publicMentions, telegramUrl } from "@/lib/site";

export function Eyebrow({ children }: { children: React.ReactNode }) { return <p className="text-xs font-bold uppercase tracking-[0.2em] text-blue-600">{children}</p>; }
export function ButtonLink({ children, href, external = false, secondary = false }: { children: React.ReactNode; href: string; external?: boolean; secondary?: boolean }) {
  const style = `inline-flex items-center justify-center gap-2 rounded-full px-5 py-3 text-sm font-bold ${secondary ? "border border-slate-200 bg-white text-slate-700 hover:border-blue-300 hover:text-blue-600" : "bg-blue-600 text-white shadow-lg shadow-blue-200 hover:bg-blue-700"}`;
  return external ? <a className={style} href={href} rel="me noopener noreferrer" target="_blank">{children}</a> : <Link className={style} href={href}>{children}</Link>;
}
export function PageHero({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) { return <section className="border-b border-slate-200 bg-white"><div className="mx-auto max-w-7xl px-5 py-18 sm:px-8 sm:py-22"><Eyebrow>{eyebrow}</Eyebrow><h1 className="mt-5 max-w-4xl text-4xl font-bold tracking-[-0.055em] text-slate-950 sm:text-6xl">{title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">{text}</p></div></section>; }
export function TelegramCallout() { return <section className="mx-auto max-w-7xl px-5 py-10 sm:px-8"><div className="relative overflow-hidden rounded-3xl bg-blue-600 px-6 py-8 text-white shadow-xl shadow-blue-200 sm:px-10 sm:py-10"><div aria-hidden="true" className="absolute -right-16 -top-20 size-64 rounded-full border-[35px] border-white/10" /><div className="relative max-w-3xl"><p className="text-xs font-bold uppercase tracking-[0.2em] text-blue-100">Official Telegram channel</p><h2 className="mt-3 text-2xl font-bold tracking-[-0.04em] sm:text-3xl">Follow sardorcodev on Telegram</h2><p className="mt-3 text-blue-100">https://t.me/sardorcodev is the official Telegram channel for sardorcodev updates and practical technology content.</p><a aria-label="Open the official sardorcodev Telegram channel in a new tab" className="mt-6 inline-flex items-center gap-2 rounded-full bg-white px-5 py-3 text-sm font-bold text-blue-700 hover:bg-blue-50" href={telegramUrl} rel="me noopener noreferrer" target="_blank"><Icon className="size-4" name="telegram" /> Open t.me/sardorcodev <Icon className="size-4" name="arrow" /></a></div></div></section>; }
export function ProfilesGrid({ showUrls = false }: { showUrls?: boolean }) { return <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{profiles.map((profile) => <a aria-label={`${profile.name}: ${profile.handle}, opens in a new tab`} className={`group rounded-2xl border bg-white p-5 hover:-translate-y-1 hover:border-blue-200 hover:shadow-lg hover:shadow-blue-100 ${profile.name === "Telegram" ? "border-blue-200" : "border-slate-200"}`} href={profile.href} key={profile.name} rel="me noopener noreferrer" target="_blank"><div className="grid size-10 place-items-center rounded-xl bg-blue-50 text-blue-600 group-hover:bg-blue-600 group-hover:text-white"><Icon className="size-5" name={profile.icon} /></div><p className="mt-5 font-bold text-slate-900">{profile.name}</p><p className="mt-1 text-sm text-slate-500">{profile.handle}</p>{showUrls ? <p className="mt-3 break-all text-xs font-semibold text-blue-600">{profile.displayUrl}</p> : null}</a>)}</div>; }
export function MentionsGrid({ limit }: { limit?: number }) { return <div className="grid gap-4 lg:grid-cols-3">{publicMentions.slice(0, limit).map((mention) => <article className="flex flex-col rounded-2xl border border-slate-200 bg-white p-6" key={mention.href}><div className="flex flex-wrap items-center gap-2"><p className="text-xs font-bold uppercase tracking-[0.15em] text-blue-600">{mention.sourceType}</p>{mention.primary ? <span className="rounded-full bg-blue-50 px-2.5 py-1 text-[0.65rem] font-bold uppercase tracking-[0.12em] text-blue-700">Primary source</span> : null}</div><h3 className="mt-5 text-xl font-bold tracking-[-0.035em] text-slate-950">{mention.title}</h3><p className="mt-3 text-sm font-bold text-slate-500">{mention.publisher}</p><p className="mt-4 flex-1 text-sm leading-6 text-slate-600">{mention.description}</p><a aria-label={`Open ${mention.title} in a new tab`} className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-blue-600 hover:text-blue-700" href={mention.href} rel="noopener noreferrer" target="_blank">View public source <Icon className="size-4" name="arrow" /></a><p className="mt-3 break-all text-xs text-slate-400">{mention.displayUrl}</p></article>)}</div>; }
